name: Cypress Tests

on:
  push:
    branches:
      - main
      - development
      - API-Voorstelling
  workflow_dispatch:


jobs:
  cypress-run:
    uses: WDPR-Groep-4/WDPR/.github/workflows/cypress.yml@CypressTests
